### ISSUE TITLE
Update Center: Upgrade issue and missing information on the Available tab

### ISSUE THREAD

**Issue by pascalberger** [racodond/sonar-json-plugin#23]
I've updated the Plugin to 2.0, afterwards Sonar fails to start with the following exception in the log:

```
java.lang.IllegalStateException: Fail to instantiate class [org.sonar.plugins.json.JSONPlugin] of plugin [json]
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:146) ~[sonar-core-5.6.jar:na]
	at org.sonar.core.platform.PluginLoader.load(PluginLoader.java:73) ~[sonar-core-5.6.jar:na]
	at org.sonar.server.plugins.ServerPluginRepository.loadInstances(ServerPluginRepository.java:288) ~[sonar-server-5.6.jar:na]
	at org.sonar.server.plugins.ServerPluginRepository.start(ServerPluginRepository.java:117) ~[sonar-server-5.6.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-5.6.jar:na]
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141) ~[sonar-core-5.6.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:84) ~[sonar-server-5.6.jar:na]
	at org.sonar.server.platform.Platform.start(Platform.java:216) ~[sonar-server-5.6.jar:na]
	at org.sonar.server.platform.Platform.startLevel2Container(Platform.java:182) ~[sonar-server-5.6.jar:na]
	at org.sonar.server.platform.Platform.init(Platform.java:91) ~[sonar-server-5.6.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-5.6.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_91]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: org.sonar.plugins.json.JSONPlugin
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:141) ~[sonar-core-5.6.jar:na]
	... 32 common frames omitted
```

System is:
Windows Server 2012 R2
Sonar 5.6
Java 8 Update 91 (64-Bit)

Any idea what might be causing this?

**Comment by racodond** [comment]
Hi @pascalberger,

The error is quite strange:

```
Caused by: java.lang.ClassNotFoundException: org.sonar.plugins.json.JSONPlugin
```

Where did you get the plugin from? Udpate Center? Github?
Did you face the same issue if you install the plugin on a fresh new instance?
Could you please provide the list of plugins that are installed on your SonarQube instance?

Thank you

David

**Comment by pascalberger** [comment]
@racodond I found the issue. It was caused by still having `sonar-json-plugin-1.4.jar` available in the `extensions\plugins` directory, besides `sonar-json-plugin-2.0.jar`. After removing this file it worked.

No idea though how this happened. I updated through the update center, and restarted afterwards from update center.

**Comment by bdetchison** [comment]
I had this same exact issue following the exact same process.  Used the same solution as @pascalberger , Thanks.

**Comment by racodond** [comment]
Thanks @pascalberger and @bdetchison for reporting the issue. The error is coming from a change in the plugin. See details at https://groups.google.com/d/msg/sonarqube/88auQtg7mxg/5vPgTkGxCQAJ

I'm gonna fix the issue and release a new version of the plugin.
