### ISSUE TITLE
StackOverflowError when too many pairs or too many values

### ISSUE THREAD

**Issue by axel3rd** [racodond/sonar-json-plugin#28]
Hi,

When a JSON file contains many key/value pairs, the analysis fails with *StackOverflowError*.

Create a file like (common usage for application translations):
```
{
 "key.0" : "value",
 "key.1" : "value",
 "key.2" : "value",
 "key.3" : "value",
 "key.4" : "value",
....
 "key.1494" : "value",
 "key.1495" : "value",
 "key.1496" : "value",
 "key.1497" : "value",
 "key.1498" : "value",
 "key.1499" : "value",
 "key.1500" : "value",
 "key.last" : "value"
}
```

The analysis fails with:
```
[INFO] [02:07:40.760] Sensor JSON Squid Sensor
[INFO] [02:07:40.765] 1 source files to be analyzed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.735 s
[INFO] Finished at: 2016-12-23T02:07:41+01:00
[INFO] Final Memory: 20M/305M
[...]
Caused by: org.apache.maven.plugin.MojoExecutionException
	at org.codehaus.mojo.sonar.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:41)
	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:139)
	at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:132)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.StackOverflowError
	at java.util.regex.Pattern.compile(Pattern.java:1683)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2380)
	at org.sonar.json.tree.impl.InternalSyntaxToken.calculateEndOffsets(InternalSyntaxToken.java:48)
	at org.sonar.json.tree.impl.InternalSyntaxToken.<init>(InternalSyntaxToken.java:44)
	at org.sonar.json.parser.JSONNodeBuilder.createTerminal(JSONNodeBuilder.java:60)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitTerminal(SyntaxTreeCreator.java:174)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:74)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.convertChildren(SyntaxTreeCreator.java:129)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:115)
  [...]
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:89)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.convertChildren(SyntaxTreeCreator.java:129)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:119)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:89)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.convertChildren(SyntaxTreeCreator.java:129)
	at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:119)
  [...]
```

**Comment by racodond** [comment]
@axel3rd 
Thanks for reporting the issue!
Same issue for too many values (arrays).
I just found the root cause and should provide a fix soon.

**Comment by axel3rd** [comment]
Thanks for the Christmas gift David :smile: (I can edit [#29](https://github.com/racodond/sonar-json-plugin/pull/29) to remove ``@Ignore`` on the test .... but *maintener* edition is open).

**Comment by racodond** [comment]
@axel3rd A snapshot is available for you to test at https://github.com/racodond/sonar-json-plugin/releases/tag/2.2-RC1

**Comment by axel3rd** [comment]
> A snapshot is available for you to test at https://github.com/racodond/sonar-json-plugin/releases/tag/2.2-RC1

I confirm the bug is fixed on the application where it occurs.

**Comment by racodond** [comment]
Cool! Thanks for the feedback!

**Comment by pietergent** [comment]
Hi, I have/had a similar problem (the same?), but unfortunately using the 2.2 RC1 does not fix the problem (although the exception is now slightly different). I get the exception underneath. Is there a way to find out which file is causing this?

```
23:55:00.941 DEBUG: Sensors : Lines Sensor -> NoSonar Sensor -> SCM Sensor -> Embedded CSS Analyzer Sensor -> JSON Squid Sensor -> Coverage Report Import -> Coverage Report Import -> Unit Test Results Import -> XmlFileSensor -> Analyzer for "php.ini" files -> Zero Coverage Sensor -> Code Colorizer Sensor -> CPD Block Indexer
23:55:00.944 INFO: Sensor Lines Sensor
23:55:01.233 INFO: Sensor Lines Sensor (done) | time=289ms
23:55:01.233 INFO: Sensor NoSonar Sensor
23:55:01.234 INFO: Sensor NoSonar Sensor (done) | time=1ms
23:55:01.234 INFO: Sensor SCM Sensor
23:55:01.234 INFO: No SCM system was detected. You can use the 'sonar.scm.provider' property to explicitly specify it.
23:55:01.234 INFO: Sensor SCM Sensor (done) | time=0ms
23:55:01.234 INFO: Sensor Embedded CSS Analyzer Sensor
23:55:01.337 INFO: 0 source files to be analyzed
23:55:01.379 INFO: Sensor Embedded CSS Analyzer Sensor (done) | time=145ms
23:55:01.379 INFO: Sensor JSON Squid Sensor
23:55:01.382 INFO: 0/0 source files have been analyzed
23:55:01.395 INFO: 2887 source files to be analyzed
Exception in thread "main" java.lang.StackOverflowError
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:91)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.convertChildren(SyntaxTreeCreator.java:129)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:119)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:89)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.convertChildren(SyntaxTreeCreator.java:129)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:119)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:89)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.convertChildren(SyntaxTreeCreator.java:129)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:119)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:89)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visit(SyntaxTreeCreator.java:72)
        at com.sonar.sslr.impl.typed.SyntaxTreeCreator.visitNonTerminal(SyntaxTreeCreator.java:97)
```

**Comment by racodond** [comment]
Hi @pietergent,

Could you please give a try to 2.2-RC2: https://github.com/racodond/sonar-json-plugin/releases/tag/2.2-RC2? It should tell you precisely which file is making the analysis crash. Then, if you can send me the file (even privately), it would be great.

Thank you

David

**Comment by pietergent** [comment]
Hi David,

Thanks, I was indeed able to find the culprit! Due to privacy reasons I cannot put the file here, but I can cleanse it and send it to you via email maybe? How can I reach you in private?

Regards,

Pieter

**Comment by racodond** [comment]
Good news Pieter!
You can send the file to me via email : david.racodon@gmail.com

**Comment by racodond** [comment]
@pietergent Your issue is due to the huge amount of nested levels of the first and unique JSON object of your file. Increasing the JVM stack size prior to running the analysis fixes your issue. For example setting the JVM stack size to 20 MB fixes the issue on my laptop. I added some details to the README file: https://github.com/racodond/sonar-json-plugin/blob/master/README.md#troubleshooting

**Comment by pietergent** [comment]
Thanks a lot! Works as a charm now!
